/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haocai_app_nativeimgcompress_utils_NativeUtil */

#ifndef _Included_com_haocai_app_nativeimgcompress_utils_NativeUtil
#define _Included_com_haocai_app_nativeimgcompress_utils_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haocai_app_nativeimgcompress_utils_NativeUtil
 * Method:    compressBitmap
 * Signature: (Landroid/graphics/Bitmap;III[BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_haocai_app_nativeimgcompress_utils_NativeUtil_compressBitmap
  (JNIEnv *, jclass, jobject, jint, jint, jint, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
